import {Shell,PageHero,Kicker,Icon,Btn} from '../components';
const IMG='https://images.pexels.com/photos/35355640/pexels-photo-35355640.jpeg?cs=srgb&dl=pexels-steve-besa-2158358525-35355640.jpg&fm=jpg';
export const metadata={title:'Organisers',description:'Event operations, attendance, briefings, scenarios and field-awareness-ready records for organisers.'};
export default function Page(){return <Shell>
<PageHero kicker="For organisers" title="Turn attendance into an organised event." text="Build the event record, connect participants and teams, control briefing and preparation, attach scenarios and activate field-awareness capability only when it adds value." image={IMG} chips={['EVENT BUILDER','CHECK-IN','BRIEFING','SCENARIOS','FIELD AWARENESS','AAR']}/>
<section className="section"><div className="section-inner"><div className="section-head"><div><Kicker>Event control</Kicker><h2>Before, during and after in one flow.</h2></div><p className="section-intro">Vanguard is designed to reduce duplicate event administration while preserving a useful record of what was planned, who attended, what capability was activated and what happened afterwards.</p></div><div className="content-grid">
<div className="content-card"><Icon name="calendar"/><h3>Event builder</h3><p>Create the event object, timings, attendance, teams, roles and controlled documents.</p></div>
<div className="content-card"><Icon name="users"/><h3>Registration & check-in</h3><p>Move from declared attendance to the actual people who arrive and participate.</p></div>
<div className="content-card"><Icon name="eye"/><h3>Briefing record</h3><p>Keep arrival instructions, organiser information and the event brief attached to the event.</p></div>
<div className="content-card"><Icon name="play"/><h3>Scenario control</h3><p>Attach reusable scenario or exercise packs, objectives, phases and event-specific control information.</p></div>
<div className="content-card"><Icon name="map"/><h3>Field-awareness activation</h3><p>Add event-scoped map and field information when the activity benefits from it.</p></div>
<div className="content-card"><Icon name="check"/><h3>Post-event record</h3><p>Retain attendance, actions and learning in the event record rather than losing it afterwards.</p></div>
</div></div></section>
<section className="section section-dark"><div className="section-inner"><div className="section-head"><div><Kicker>Product truth</Kicker><h2>Live capability and future sector workflows stay separate.</h2></div><p className="section-intro">Current sports/event capability and the ATAC field layer are the strongest live proof. Training and readiness workflows are being adapted and validated rather than presented as finished emergency systems.</p></div><div className="actions"><Btn href="/sectors">Explore use cases</Btn></div></div></section>
<section className="band"><div className="band-inner"><h2>Run the event. Keep the useful record.</h2><Btn href="/pricing">See organiser pricing</Btn></div></section>
</Shell>}