import {Shell,Kicker,Btn,ProductCard,ImagePanel,Metric,Icon} from './components';

const HERO='https://images.pexels.com/photos/3706636/pexels-photo-3706636.jpeg?cs=srgb&dl=pexels-kony-xyzx-2079231-3706636.jpg&fm=jpg';
const TEAM='https://images.pexels.com/photos/20335224/pexels-photo-20335224.jpeg?cs=srgb&dl=pexels-gmb-visuals-564876670-20335224.jpg&fm=jpg';
const TEAM2='https://images.pexels.com/photos/20335223/pexels-photo-20335223.jpeg?cs=srgb&dl=pexels-gmb-visuals-564876670-20335223.jpg&fm=jpg';

export default function Home(){return <Shell>
<section className="hero"><div className="hero-copy"><div className="hero-logo-lockup" role="img" aria-label="Vanguard Tactical logo"></div><Kicker>VANGUARD TACTICAL / UNITED KINGDOM</Kicker><h1>BUILD THE TEAM.<br/><em>EQUIP THE TEAM.</em><br/>RUN THE EVENT.</h1><p>One connected operating environment for organised airsoft teams, equipment, events and field operations. Plan the weekend, see what is missing, give everyone the same information and keep improving.</p><div className="hero-actions"><Btn href="/pricing">BUILD YOUR TEAM</Btn><Btn href="/team-os" secondary>SEE HOW IT WORKS</Btn></div></div><div className="hero-visual" style={{backgroundImage:`url('${HERO}')`}}><div className="hero-stamp"><small>VANGUARD / FIELD SYSTEM</small><b>CONNECTED. CONTROLLED. READY.</b></div></div></section>
<div className="metric-strip"><Metric value="01" label="Team workspace"/><Metric value="02" label="Equipment system"/><Metric value="03" label="Event control"/><Metric value="04" label="Field backbone"/></div>
<section className="section"><div className="section-head"><div><Kicker>THE OPERATING LAYER</Kicker><h2>YOUR TEAM SHOULD NOT NEED SIX APPS TO RUN ONE WEEKEND.</h2></div><p className="section-intro">WhatsApp. Spreadsheets. Payment links. Equipment notes. Maps. Event PDFs. Vanguard does not try to replace every specialist tool. It gives the team one operating picture and connects the information that matters.</p></div><div className="products"><ProductCard icon="users" tag="VANGUARD OS" title="One team. One workspace." href="/team-os">Roster, availability, events, training, actions, documents and member dashboards.</ProductCard><ProductCard icon="box" tag="VANGUARD ARMOURY" title="Know what you have." href="/armoury">Personal kit, team assets, Vanguard hire, issue, return, condition and equipment gaps.</ProductCard><ProductCard icon="calendar" tag="VANGUARD EVENTS" title="One source of truth." href="/events">Attendance, brief, timings, kit, comms, actions and approved event information.</ProductCard><ProductCard icon="radio" tag="VANGUARD CONTROL" title="Less admin. Better answers." href="/control">Approved event-context assistance that answers what it knows and routes what it does not.</ProductCard><ProductCard icon="signal" tag="VANGUARD FIELD" title="No signal should not mean no system." href="/field">Portable connectivity and rugged event-control infrastructure for remote sites.</ProductCard><ProductCard icon="map" tag="VANGUARD OPS" title="Connect mature tools." href="/control">Prepare team structure, approved locations and exports for mapping and operational tools.</ProductCard></div></section>
<section className="section section-dark"><div className="split"><ImagePanel image={TEAM2} label="TEAM OS / MEMBER EXPERIENCE" title="ONE TEAM. ONE WORKSPACE."/><div><Kicker>MY VANGUARD</Kicker><h2>THE MEMBER VIEW THAT REPLACES SCROLLING THROUGH OLD CHAT.</h2><p>Every member gets a mobile-first dashboard for the next event: assignment, actions, booked hire, issued kit, training, documents and announcements. Built as a PWA so the first release can live on a phone without waiting for an app-store launch.</p><div className="feature-list"><div className="feature-row"><span className="num">01</span><b>Next event & assignment</b><span>LIVE VIEW</span></div><div className="feature-row"><span className="num">02</span><b>Kit gap & reservations</b><span>CONNECTED</span></div><div className="feature-row"><span className="num">03</span><b>Actions & training</b><span>PERSONAL</span></div><div className="feature-row"><span className="num">04</span><b>Briefs & documents</b><span>CONTROLLED</span></div></div><div className="actions"><Btn href="/workspace">VIEW WORKSPACE DEMO</Btn></div></div></div></section>
<section className="section"><div className="split"><div><Kicker>EQUIPMENT REQUIREMENT ENGINE</Kicker><h2>KNOW WHAT YOU HAVE. KNOW WHAT YOU NEED.</h2><p>Vanguard compares who is attending, what each member owns and what the event requires. The result is an equipment gap that can become a reservation, hire package or future purchase journey.</p><div className="steps"><div className="step"><b>01 / ATTEND</b><h3>WHO IS COMING?</h3><p>Confirmed roster and roles.</p></div><div className="step"><b>02 / OWN</b><h3>WHAT EXISTS?</h3><p>Member and team equipment.</p></div><div className="step"><b>03 / NEED</b><h3>WHAT IS MISSING?</h3><p>Event-required capability.</p></div><div className="step"><b>04 / FILL</b><h3>VANGUARD PACKAGE</h3><p>Reserve, hire or source it.</p></div></div></div><ImagePanel image={TEAM} label="ARMOURY / EQUIPMENT" title="TRY → HIRE → JOIN → BUY"/></div></section>
<section className="section section-dark"><div className="section-head"><div><Kicker>BUILT IN THE FIELD</Kicker><h2>6 TROOP IS THE FIRST LIVE PROVING TEAM.</h2></div><div><p className="section-intro">Vanguard is not software designed in isolation. 6 Troop uses the same platform to organise its own events, people, equipment and training. 7 Troop provides reserve and augmentation capacity as the model develops.</p><div className="actions"><Btn href="/6-troop">MEET 6 TROOP</Btn></div></div></div><ImagePanel image={TEAM2} label="6 TROOP / SPORTING AIRSOFT" title="THE TEAM, NOT THE EQUIPMENT, IS THE HERO" className="wide-image"/></section>
<section className="band"><h2>SOFTWARE WHEN YOU NEED ORGANISATION. EQUIPMENT WHEN YOU NEED CAPABILITY.</h2><Btn href="/pricing">VIEW LAUNCH PRICING</Btn></section>
</Shell>}
