import {Shell,PageHero,Kicker,Btn,Icon} from '../components';
const IMG='https://images.pexels.com/photos/20335223/pexels-photo-20335223.jpeg?auto=compress&cs=tinysrgb&w=1800';
const packs=[['Viper Strike','Convoy escort, disruption and recovery.','4–6 hours'],['Sentinel Line','Border-sector patrol, checkpoints and infrastructure pressure.','8–12 hours'],['Black Box','Downed-aircraft recovery and search-sector race.','6–10 hours']];
export const metadata={title:'Scenarios',description:'Reusable Vanguard scenario packs and game-mode concepts for organised airsoft events.'};
export default function Page(){return <Shell>
<PageHero kicker="Vanguard scenarios" title="Do not just book a game day. Run an experience." text="Scenario packs are reusable event IP: organiser guidance, factions, objectives, injects, scoring and optional ATAC layers — structured as executable event packages rather than PDFs alone." image={IMG} chips={['MISSION PACKS','CAMPAIGNS','ATAC-ENHANCED','EVENT CONTROL']}/>
<section className="section"><div className="section-inner"><div className="section-head"><div><Kicker>Alpha library</Kicker><h2>First concept packs.</h2></div><p className="section-intro">These remain prototype concepts rather than finished paid products. Each pack is intended to become a repeatable event package with clear organiser controls and truth-labelled optional capability.</p></div><div className="content-grid">{packs.map(([t,d,h])=><div className="content-card" key={t}><Icon name="play"/><span className="eyebrow">Prototype</span><h3>{t}</h3><p>{d}</p><p><b>{h}</b></p></div>)}</div></div></section>
<section className="section section-dark"><div className="section-inner"><div className="section-head"><div><Kicker>Future intelligent control</Kicker><h2>AI Commander, OPFOR and Umpire remain clearly labelled until field-tested.</h2></div><p className="section-intro">Vanguard can develop assisted event-control concepts, but simulated or future capability must never be presented as field-proven functionality before it is actually built and tested.</p></div></div></section>
<section className="band"><div className="band-inner"><h2>Build the event around more than a PDF.</h2><Btn href="/signup">Join the alpha</Btn></div></section>
</Shell>}